### ISSUE TITLE
reportMissingImports

### ISSUE THREAD

**Issue by De3ph** [AndersonFirmino/flask-google-recaptcha#3]
When i tried to import, it gives error on urllib2.
![Screenshot from 2021-08-19 21-00-19](https://user-images.githubusercontent.com/62203579/130120710-64847784-d653-498e-b016-37139a37addf.png)

**Comment by AndersonFirmino** [comment]
You added an unnecessary character at the end of line 23. I did the tests here and the library still works even after so long. 
Thanks for the issue
